
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: 129390742221.dkr.ecr.eu-north-1.amazonaws.com/asg
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask
    k8s-app: flask
  name: flask
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: flask
